[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
il_protection = "pVdRxAaaKsbhhZoMpmZsBaUBxtGd3TZCsVzFbmwhioh"

[programs.localnet]
il_protection = "78sDjTrYfZnn8VmbuPNRJ2QRy3m8L4tn1tcZE7WihUdX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/turbin3-wallet.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
